services:
  testwork-postgres:
    image: postgres:17
    container_name: testwork-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./infrastructure/databases/testwork:/docker-entrypoint-initdb.d:ro
      - testwork_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  testwork_data: